### PR TITLE
add binary write/read

### PR DESCRIPTION
**Pull request by okdistribute**
can you look this over?

### CODE REVIEW

**Comment by jeroenooms** [comment]
Yes, sry for the delay; need to finish up something else right now, but will review asap :)

**Comment by karthik** [comment]
@karissa Is the `version` argument not looking to check for any specific version? Right now I cioul give it just about any value and it would execute the else part.

**Comment by jeroenooms** [comment]
Okay i'm going to look at this now...

**Comment by karissa** [comment]
@karthik a version is only ever a 64 bit hash at the moment

**Comment by jeroenooms** [comment]
Is the default executable still called `dat-beta` ? Or just `dat` ?

**Comment by karissa** [comment]
You can install from master now and it is called dat! We merged it
yesterday

**Pull request merged**
