### PR TITLE
Add a preliminary api

### PR DESCRIPTION
**Pull request by okdistribute**

### CODE REVIEW

**Comment by karissa** [comment]
@karthik can you give me some feedback? i'm not a regular R user so I defer to your judgement

**Comment by karissa** [comment]
cc @maxogden

**Comment by karthik** [comment]
Sure thing @karissa 
Will respond as soon as I have a chance to look this over.

**Comment by karthik** [comment]
Hey @karissa 

Some feedback. 

`dat = rDat.clone('ssh://path/to/dat')`

Replace the `=` signs (outside of function arguments) to `<- ` the R assignment operator.

Generic verbs like push, pull and get should be renamed with some `dat` prefix, e.g. `dat_push`, `dat_pull` etc to avoid conflict with packages that might have related operations (e.g. various git wrappers).

Also good to avoid mixed patterns for function names. Either stick with lower case, snake_case (recommended) or camelCase (avoid if possible). 

But otherwise this looks like a good roadmap. If you can standardize the names, I'll merge this PR in.

**Comment by karissa** [comment]
Sorry for the lateness @karthik but i updated to the spec to your comments but also to be more generic.

**Comment by karthik** [comment]
No worries and thanks @karissa

**Pull request merged**
